Vimc 7111: initial version of package vacsce
vimc/vacsce pull request #1
Opened 2023-08-02 13:56 UTC by xiangli313

Dear all,

This PR is related to the initial set-up of package names ```vacsce```. 

This package stores coverage projection rules. We intend to wrap them up as a package usable by both internal and external users.

Thanks!

2023-08-04 09:17 UTC, richfitz requested changes
Hi Xiang - some general comments here for you to consider. I'm sure Katy will have comments on the data processing code. I presume this has come from some previous report or import that you've consolidated?

Some of the comments are only written once but apply throughout (comments on paste, ifelse, etc). The section with the eval(parse()) is worth thinking about carefully.

Happy to loop back on this next week, but there's a chance I may be away

2023-08-04 09:17 UTC, richfitz commented on R/general.R
> +    print("No historical routine data identified.")
prefer `message()` to `print()`

Is continuing here what you really want to do?

2023-08-04 09:17 UTC, richfitz commented on R/general.R
> +    mutate(coverage = ifelse(activity_type == "routine", coverage/input$params$proportion_risk, coverage))
I think that `dplyr::case_when` is the preferred way of doing this, `ifelse` has lots of problems. @kgaythorpe would know better than me though

2023-08-04 09:17 UTC, richfitz commented on R/general.R
> +  his <- input$his
personally, I would expand these sorts of names to `history` and `future` because they're not much longer but easier to work with

2023-08-04 09:17 UTC, richfitz commented on R/util.R
> +IA2030_projection <- function(t0, c0, T, cT){
I'd be careful not to use `T` here for the name, it looks like `TRUE` (see the syntax highlighting here pushing you this way). More descriptive names in general would help if you needed someone like me to help with the function in the future

2023-08-04 09:17 UTC, richfitz commented on R/test_tool.R
> +# rm(list = ls())
This file should be deleted.

2023-08-04 09:17 UTC, richfitz commented on R/projection_rules.R
> +  t <- NULL
```suggestion
  year <- NULL
```

(and then below when used) so that later you go


```
  t <- data.frame(year = year,
                  coverage = sia_level,
                  age_from = age_from,
                  age_to = age_to,
                  gender = gender)
```

which will be easier to work with in a year's time

2023-08-04 09:17 UTC, richfitz commented on R/projection_rules.R
> +    cov[1] <- vaccine_x_level*intro_level # intro at 33% of target vaccine
```suggestion
    cov[1] <- vaccine_x_level*intro_level # intro at 33% of target vaccine by default (see args)
```

2023-08-04 09:17 UTC, richfitz commented on R/projection_rules.R
> +    merge(data.frame(year = year_from:year_to)) %>%
I believe (and again would defer to @kgaythorpe) that one of the dplyr join functions here is preferable

2023-08-04 09:17 UTC, richfitz commented on R/general.R
> +  t <- data.frame(region = c(324, 324, 324, 50, 50, 108, 108),
Some explanation as to the origin of these numbers is essential

2023-08-04 09:17 UTC, richfitz commented on R/general.R
> +      }
I am not at all sure what this is trying to do but:

* the print statement suggests it's fairly tricky and took a while to work out :)
* there is probably a better way of doing it that will be easier to understand and more robust

Can you try and describe what is going on, and perhaps I can come up with some easier way

2023-08-04 09:17 UTC, richfitz commented on dettl_config.yml
> +db:
why is there a dettl config here? that should be only in montagu-imports surely?

2023-08-04 09:17 UTC, richfitz commented on tests/testthat/test-vacsce-generation.R
Empty file - delete or write some tests :)

2023-08-04 09:17 UTC, richfitz commented on vignettes/Using vacsce for vaccination coverage scenario generation.html
Delete generated files

2023-08-04 09:17 UTC, richfitz commented on DESCRIPTION
> +Package: vacsce
Can you enable some standard github actions please:

```
usethis::use_github_action("pkgdown")
usethis::use_github_action("test-coverage")
usethis::use_github_action_check_standard()
```

then push the result up to github (will be a .github) directory. Most likely they will fail, but do so informatively

2023-08-04 09:17 UTC, richfitz commented on NAMESPACE
> +# Generated by roxygen2: do not edit by hand
Your package exports no functions, which means it has no interface. Add `#' @export` tags to the functions you want to export and redocument

2023-08-04 09:17 UTC, richfitz commented on .gitignore
> +.Rproj.user
Please add a basic README.md at the top level

2023-08-07 07:29 UTC, kgaythorpe commented on R/general.R
> +      summarise(year_intro_src = min(year), .groups = "keep") %>%
also a dplyr function, summarise

2023-08-07 07:30 UTC, kgaythorpe commented on R/general.R
> +    mutate(coverage = ifelse(activity_type == "routine", coverage/input$params$proportion_risk, coverage))
not sure if captured later but does this protect against dividing by 0

2023-08-07 07:31 UTC, kgaythorpe commented on R/general.R
> +      dat <- bind_rows(dat, d0, d1)
dplyr::bind_rows

2023-08-07 07:32 UTC, kgaythorpe commented on R/general.R
> +          merge(input$introduction[i, c("vaccine", "activity_type")]) %>%
would stick to dplyr consistently rather than merge- fewer moving parts for things going wrong due to packages

2023-08-07 07:33 UTC, kgaythorpe commented on R/general.R
> +  t <- data.frame(region = c(324, 324, 324, 50, 50, 108, 108),
agreed though as this is example data, these numbers could just be randomly generated

2023-08-07 07:33 UTC, kgaythorpe commented on R/general.R
> +  d <- DBI::dbGetQuery(con,
is this just to generate data that will be included in the package or is this something that is going to be a problem for users without access to the database

2023-08-07 07:34 UTC, kgaythorpe commented on R/general.R
> +    right_join(t, by = c("region", "vaccine", "activity_type")) %>%
more dplyr- mutate, right_join

2023-08-07 07:35 UTC, kgaythorpe commented on R/projection_rules.R
> +    merge(data.frame(year = year_from:year_to)) %>%
agreed

2023-08-07 07:36 UTC, kgaythorpe commented on R/projection_rules.R
> +  y <- max(d$year)
could this be renamed max_y for easier reading

2023-08-07 07:36 UTC, kgaythorpe commented on R/projection_rules.R
> +  t <- d[d$year == y, ] %>%
would rename t for easier reading

2023-08-07 07:39 UTC, kgaythorpe commented on R/util.R
> +IA2030_projection <- function(t0, c0, T, cT){
agreed, also minor comment- could use lower case name for function for consistency- would also add citation to the ia2030 paper (Carter et al. 2023 https://www.sciencedirect.com/science/article/pii/S0264410X2300854X)

2023-08-07 07:39 UTC, kgaythorpe commented on R/util.R
> +vimc_historical_data <- function(con, year_cur, coverage_src_his, coverage_src_fut){
worth having this not export or adding a message ("this is for VIMC internal use only")

2023-08-07 07:42 UTC, kgaythorpe commented on vignettes/vignette.Rmd
> +This vignette describes how to use **vacsce** to generate vaccination coverage scenarios. **vacsce** provides a set of coverage projection rules. Its initial objective was to document commonly used c
add something like "vasce stands for vaccination scenarios" so people know how to say it

2023-08-07 07:44 UTC, kgaythorpe commented on vignettes/vignette.Rmd
> +In the case where routine introduction has had happened. The projection rule will **non-linearly scale-up** to the target **vaccine_x_level** from **year_from-1**, hence one needs to make sure there
*has happened

2023-08-07 07:47 UTC, kgaythorpe commented on vignettes/vignette.Rmd
> +Example one works as a null run of **vacsce**. Without specification of projection rules, the package simply bind any historical and future coverage sources. In practice, a null run may be not useful
*will simply

2023-08-07 07:47 UTC, kgaythorpe commented on vignettes/vignette.Rmd
> +Example one works as a null run of **vacsce**. Without specification of projection rules, the package simply bind any historical and future coverage sources. In practice, a null run may be not useful
However, for VIMC users, a null run works by combining historical and future from two data sources (e.g. touchstones).]

2023-08-07 07:49 UTC, kgaythorpe commented on vignettes/vignette.Rmd
> +Comparing with example 3, example 4 have an additional campaign projection rule which projects future recurrent follow-up SIAs. Since campaign projection is dependent on routine projection, **vacsce*
I would cut the"you do not need to worry" bit- as it sounds contradictory to the following sentence

2023-08-11 10:20 UTC, xiangli313 commented on DESCRIPTION
> +Package: vacsce
Done.

2023-08-11 10:21 UTC, xiangli313 commented on NAMESPACE
> +# Generated by roxygen2: do not edit by hand
Done.

2023-08-11 10:21 UTC, xiangli313 commented on R/general.R
> +      summarise(year_intro_src = min(year), .groups = "keep") %>%
Done.

2023-08-11 10:21 UTC, xiangli313 commented on R/general.R
> +  his <- input$his
Done.

2023-08-11 10:21 UTC, xiangli313 commented on R/general.R
> +      dat <- bind_rows(dat, d0, d1)
Done.

2023-08-11 10:21 UTC, xiangli313 commented on R/general.R
> +          merge(input$introduction[i, c("vaccine", "activity_type")]) %>%
Done.

2023-08-11 10:21 UTC, xiangli313 commented on R/general.R
> +  t <- data.frame(region = c(324, 324, 324, 50, 50, 108, 108),
These are country.nid in montagu. Added notes for this.

2023-08-11 10:21 UTC, xiangli313 commented on R/general.R
> +  d <- DBI::dbGetQuery(con,
This is just to generate example data for people who use this package. It is run only once. Using the package does not need access to the database.

2023-08-11 10:21 UTC, xiangli313 commented on R/general.R
> +    right_join(t, by = c("region", "vaccine", "activity_type")) %>%
Done.

2023-08-11 10:21 UTC, xiangli313 commented on R/projection_rules.R
> +    merge(data.frame(year = year_from:year_to)) %>%
Done.

2023-08-11 10:21 UTC, xiangli313 commented on R/projection_rules.R
> +  y <- max(d$year)
Done.

2023-08-11 10:22 UTC, xiangli313 commented on R/projection_rules.R
> +  t <- d[d$year == y, ] %>%
Added a note : "this is just to grab one row in source data for information like region, vaccine, activity_type, age groups, etc."

2023-08-11 10:22 UTC, xiangli313 commented on R/projection_rules.R
> +  t <- NULL
Done.

2023-08-11 10:22 UTC, xiangli313 commented on R/util.R
> +IA2030_projection <- function(t0, c0, T, cT){
renamed to year_base, coverage_base, year_target, and coverage_target.

2023-08-11 10:22 UTC, xiangli313 commented on dettl_config.yml
> +db:
It was only used while extracting sample data for developing the package. Removed now.

2023-08-11 11:26 UTC, xiangli313 commented on R/util.R
> +vimc_historical_data <- function(con, year_cur, coverage_src_his, coverage_src_fut){
This is removed. It was the initial function extracting example data.

2023-08-11 11:27 UTC, xiangli313 commented on vignettes/vignette.Rmd
> +This vignette describes how to use **vacsce** to generate vaccination coverage scenarios. **vacsce** provides a set of coverage projection rules. Its initial objective was to document commonly used c
Done.

2023-08-11 11:29 UTC, xiangli313 commented on vignettes/vignette.Rmd
> +In the case where routine introduction has had happened. The projection rule will **non-linearly scale-up** to the target **vaccine_x_level** from **year_from-1**, hence one needs to make sure there
I have a lot of double ** to make bold characters in html output.

2023-08-11 11:29 UTC, xiangli313 commented on vignettes/vignette.Rmd
> +Example one works as a null run of **vacsce**. Without specification of projection rules, the package simply bind any historical and future coverage sources. In practice, a null run may be not useful
Done.

2023-08-11 11:30 UTC, xiangli313 commented on vignettes/vignette.Rmd
> +Comparing with example 3, example 4 have an additional campaign projection rule which projects future recurrent follow-up SIAs. Since campaign projection is dependent on routine projection, **vacsce*
Done.

2023-08-11 11:31 UTC, xiangli313 commented on tests/testthat/test-vacsce-generation.R
Deleted.

2023-08-11 11:31 UTC, xiangli313 commented on vignettes/Using vacsce for vaccination coverage scenario generation.html
Done.

2023-08-11 11:35 UTC, xiangli313 commented on .gitignore
> +.Rproj.user
There is a README.md in vacsce/ directory. Is that what you mean?

2023-08-11 11:36 UTC, xiangli313 commented on R/general.R
> +    mutate(coverage = ifelse(activity_type == "routine", coverage/input$params$proportion_risk, coverage))
There is this code above - stopifnot(proportion_risk <= 1 & proportion_risk > 0) # proportion of at risk population. This makes sure proportion_risk is meaningfully within (0, 1].

2023-08-11 11:48 UTC, xiangli313 commented
Hi Rich and Katy,

I think I have addressed most of your comments. 

Rich. The section with `eval(parse())` is one that I need your help with. The aim is to evaluate function and corresponding parameters from a string. So that a user can specify input in a standardise way, and let the package handle the rest. An example might be helpful here.
A user defines projection rules in the following set-up
```
rules = list(
          catch_up_with_x = list(year_from = 2027, year_to = 2030, vaccine_x_level = 0.7, age_from = 0, age_to = 0, gender = 3),
           non_linear_scale_up = list(year_from = 2031, year_to = 2035, endpoint = 0.9, age_from = 0, age_to = 0, gender = 3)
)
```
Then, `eval(parse())` would interpret the above set-up as 1.) there are two projection rules/functions, `catch_up_with_x` and `non_linear_scale_up`; 2.) each rule/function has a set of parameters specified as a list.  

I cannot think of a more robust way of doing this. Please let me know if you had a better approach for me to get on.

2023-09-04 14:58 UTC, richfitz requested changes
some small comments here that should help get the checks passing - you should see a series of red 'x's on your PR that if you click through will show you issues.

You can run these locally by running `devtools::check()`

2023-09-04 14:58 UTC, richfitz commented on README.md
> +## Objectives
this file should contain installation instructions (at a minimum, instructions for using `remotes`)

2023-09-04 14:58 UTC, richfitz commented on vignettes/vignette.Rmd
> +data <- read.csv("../inst/example_data.csv")
```suggestion
data <- system.file("example_data.csv", package = "vacsce", mustWork = TRUE)
```

2023-09-04 14:58 UTC, richfitz commented on vignettes/vignette.Rmd
> +dat <- keep_levels(d, year_from = year_cur + 1,
This won't work unless the package is loaded - you have that commented out in a hidden section above, so I suggest you put a non-hidden call to `library(vasce)` somewhere in the doc. The aim is that an interested user can follow along

2023-09-04 14:58 UTC, richfitz commented on vignettes/vignette.Rmd
> +In the case where routine introduction has had happened. The projection rule will **non-linearly scale-up** to the target **vaccine_x_level** from **year_from-1**, hence one needs to make sure there
Katy means that this should say

```suggestion
In the case where routine introduction has happened. The projection rule will **non-linearly scale-up** to the target **vaccine_x_level** from **year_from-1**, hence one needs to make sure there is a coverage value in **year_from -1**. A message will show up saying that parameter **intro_level** is not applicable and not used. (N.B. **non-linearly scale-up** refers to the next generation rule to be introduced.)
```

the `*` she uses there just indicates a correction, not the bolding

2023-09-04 14:58 UTC, richfitz commented on R/general.R
> +#' <- list(country = "<country_code>",
This does not look right at all, and is causing the failing check with documentation I think. I'm not sure what you're trying to say here either so can't offer a concrete suggestion.

2023-09-08 14:17 UTC, richfitz approved these changes

2023-09-08 14:45 UTC, merged